modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
description = "Unofficial NeoForge Port of the AudioPlayer mod made by henkelmax and BreadLoaf with updates to make it so the disks behave more like vinilla music box disks instead of custom Voice Chat mod audio."
authors = "Duncan Jones"

[[mixins]]
config = "apneoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"